image: docker:latest
services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -f tibco.bwce.sample.binding.soap.http.ZipCodeServiceProvider.application -DskipTests"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
#  DOCKER_OPTS: "-Ddocker.username=jolokia -Ddocker.password=s!cr!t" 
  DOCKER_OPTS: "-u $DOCKER_USER -p $DOCKER_PASSWORD" 
  DOCKER_HOST: tcp://docker:2375/
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - package
  - deploy

before_script:
  - docker info
   
maven-build:
  stage: build
  image: maven:3-jdk-8
  script:
   - mvn $MAVEN_CLI_OPTS clean initialize package install 

docker-build:
  stage: package
  script:
   - docker login -u mbloomfi@tibco.com -p Tibco123 nexus.tibcopsg.net:18079
   - docker build -t nexus.tibcopsg.net/bwce/zipcodeexample:latest .
   - docker push nexus.tibcopsg.net/bwce/zipcodeexample:latest

#build:
#  stage: build
# script:
#   - mvn $MAVEN_CLI_OPTS -Dfabric8.build.pullSecret=$DOCKER_PASSWORD -Ddocker.username=$DOCKER_USER -Ddocker.password=$DOCKER_PASSWORD clean initialize package install docker:build docker:push

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS $DOCKER_OPTS deploy

#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master