image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -f tibco.bwce.sample.binding.soap.http.ZipCodeServiceProvider.application.parent -DskipTests"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_OPTS: "-Ddocker.username=jolokia -Ddocker.password=s!cr!t" 

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -Ddocker.username=$DOCKER_USER -Ddocker.password=$DOCKER_PASSWORD clean initialize package install docker:build docker:push

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS $DOCKER_OPTS deploy

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master