image: docker:latest
services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -f tibco.bwce.sample.binding.soap.http.ZipCodeServiceProvider.application"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_OPTS: "-u $DOCKER_USER -p $DOCKER_PASSWORD" 
  DOCKER_HOST: tcp://localhost:2375
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - package
  - test
  - deploy

maven-build:
  stage: build
  image: maven:3-jdk-8
  script:
   - mvn $MAVEN_CLI_OPTS -DskipTests clean initialize package install deploy
  artifacts:
    name: "intsearchui-$CI_BUILD_ID-$CI_BUILD_REF"
    expire_in: 1 day
    paths:
     - tibco.bwce.sample.binding.soap.http.ZipCodeServiceProvider.application/target/*.ear

docker-build:
  stage: package
  script:
   - docker login -u mbloomfi@tibco.com -p Tibco123 nexus.tibcopsg.net:18079
   - docker build -t nexus.tibcopsg.net:18079/bwce/zipcodeexample:latest .
   - docker push nexus.tibcopsg.net:18079/bwce/zipcodeexample:latest
   - docker tag nexus.tibcopsg.net:18079/bwce/zipcodeexample:latest mbloomfi/zipcodeexample:latest
   - docker login -u mbloomfi -p Iamcrazy01 docker.io
   - docker push mbloomfi/zipcodeexample:latest

hadolint:
  stage: test
  image: pipelinecomponents/hadolint:latest
  script:
    - hadolint Dockerfile

run-code-quality-check:
  stage: test
  image: maven:3-jdk-8
  script:
    - mvn -s .m2/settings.xml --batch-mode -f tibco.bwce.sample.binding.soap.http.ZipCodeServiceProvider sonar:sonar 

#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master