image: docker:latest
services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -f tibco.bwce.sample.binding.soap.http.ZipCodeServiceProvider.application"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
#  DOCKER_OPTS: "-Ddocker.username=jolokia -Ddocker.password=s!cr!t" 
  DOCKER_OPTS: "-u $DOCKER_USER -p $DOCKER_PASSWORD" 
  DOCKER_HOST: tcp://localhost:2375
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - package
  - test
  - deploy

 #before_script:
 #  - docker info
   
maven-build:
  stage: build
  image: maven:3-jdk-8
  script:
   - mvn $MAVEN_CLI_OPTS -DskipTests clean initialize package install
   
maven-deploy-nexus: 
  stage: package
  image: maven:3-jdk-8
  script:
   - mvn $MAVEN_CLI_OPTS -DskipTests clean initialize install deploy

docker-build:
  stage: package
  script:
   - docker login -u mbloomfi@tibco.com -p Tibco123 nexus.tibcopsg.net:18079
   - docker build -t nexus.tibcopsg.net:18079/bwce/zipcodeexample:latest .
   - docker push nexus.tibcopsg.net:18079/bwce/zipcodeexample:latest

run-unit-tests:
  stage: test
  image: maven:3-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS test

#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master